---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name : Working terminal
    command: echo "Working terminal"
  - name: Npm Init for nextjs-blog
    init: npm install # runs during prebuild
    command: npm run dev
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - dcasella.monokai-plusplus
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-complete-tag
    - formulahendry.auto-rename-tag
    - kamikillerto.vscode-colorize
    - rangav.vscode-thunder-client
    - aaron-bond.better-comments
