---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name : Working terminal Front
    command: echo "Working terminal front"
  - name: Npm Init for nextjs-blog
    init: cd front && npm install # runs during prebuild
    command: npm run dev
    openMode: split-right
  - name: Working terminal Back
    init: cd back && cargo build # runs during prebuild
    command: echo "Working terminal back"
    openMode: tab-after

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: notify

vscode:
  extensions:
    - dcasella.monokai-plusplus
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-complete-tag
    - formulahendry.auto-rename-tag
    - kamikillerto.vscode-colorize
    - rangav.vscode-thunder-client
    - aaron-bond.better-comments
    - rust-lang.rust-analyzer
    - usernamehw.errorlens
    - belfz.search-crates-io
    - bungcip.better-toml